version: '3'

services:
  db:
    image: mysql:5.6
    container_name: mysql-db-container
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password@root123
      MYSQL_DATABASE: sakila
    ports: 
      - "80:3306"
    volumes: 
      - ./db/sakila-data.sql:/docker-entrypoint-initdb.d/sakila-data.sql

  atlan-app:
    build: .
    restart: always
    container_name: atlan-app-container
    ports: 
      - 9000:3000
    links: 
      - db:db
    depends_on: 
      - db
    